spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${DB_PLATFORM}
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  main:
    allow-bean-definition-overriding: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}


jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}
  time:
    accessExp: ${JWT_ACCESS_TIME}
    refreshExp: ${JWT_REFRESH_TIME}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}